-- Create all tables referenced by controllers that are missing from the schema
-- Generated by analyzing every controller's supabaseAdmin.from('tablename') calls

-- 1. wallet_transactions: used by walletController (withdraw, transfer, getStatistics) and webhooksController
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  type TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending',
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. escrow_history: used by escrowController.getEscrowStatus
CREATE TABLE IF NOT EXISTS escrow_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  escrow_id UUID NOT NULL REFERENCES escrows(id),
  from_status TEXT,
  to_status TEXT,
  changed_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. escrow_disputes: used by escrowController (raiseDispute, adminListPendingDisputes)
CREATE TABLE IF NOT EXISTS escrow_disputes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  escrow_id UUID NOT NULL REFERENCES escrows(id),
  reason TEXT NOT NULL,
  details TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. payments: used by paymentsController.verifyPayment
CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reference TEXT NOT NULL,
  status TEXT,
  amount NUMERIC,
  customer JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. payment_methods: used by paymentsController (saveCard, getSavedMethods, deleteMethod)
CREATE TABLE IF NOT EXISTS payment_methods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  type TEXT NOT NULL,
  authorization_code TEXT,
  last4 TEXT,
  exp TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. kyc_documents: rename + extend kyc_submissions
-- Drop the old table (nothing references it) and create the proper one
DROP TABLE IF EXISTS kyc_submissions;
CREATE TABLE IF NOT EXISTS kyc_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE,
  id_type TEXT,
  id_number TEXT,
  id_front_url TEXT,
  id_back_url TEXT,
  selfie_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  admin_notes TEXT,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 7. emergency_alerts: used by emergencyController (triggerSos, cancelSos, getAlertStatus)
CREATE TABLE IF NOT EXISTS emergency_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  location TEXT,
  booking_id UUID,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 8. emergency_contacts: used by emergencyController (getEmergencyContacts, addContact, updateContact, deleteContact)
CREATE TABLE IF NOT EXISTS emergency_contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  relationship TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 9. emergency_responders: used by emergencyController.getAlertStatus
CREATE TABLE IF NOT EXISTS emergency_responders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_id UUID NOT NULL REFERENCES emergency_alerts(id),
  contact_id UUID NOT NULL,
  contacted_at TIMESTAMPTZ DEFAULT now(),
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 10. tracking_sessions: used by trackingController (startTracking, updateLocation, getLiveLocation, getLocationHistory, endTracking)
CREATE TABLE IF NOT EXISTS tracking_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id UUID NOT NULL,
  driver_id UUID NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  last_lat DOUBLE PRECISION,
  last_lng DOUBLE PRECISION,
  last_updated_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 11. tracking_locations: used by trackingController (startTracking, updateLocation, getLocationHistory)
CREATE TABLE IF NOT EXISTS tracking_locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tracking_id UUID NOT NULL REFERENCES tracking_sessions(id),
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  timestamp TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 12. tracking_deviations: used by trackingController.reportDeviation
CREATE TABLE IF NOT EXISTS tracking_deviations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id UUID NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'reported',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 13. bill_transactions: used by billsController (buyAirtime, buyData, payElectricity, getBillHistory)
CREATE TABLE IF NOT EXISTS bill_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  type TEXT NOT NULL,
  phone TEXT,
  network TEXT,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 14. route_feed_statuses: used by routeFeedController (createStatus, getFeed, getRouteStatuses, getStatus, deleteStatus)
CREATE TABLE IF NOT EXISTS route_feed_statuses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  route TEXT NOT NULL,
  content TEXT,
  image TEXT,
  type TEXT NOT NULL DEFAULT 'text',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 15. route_feed_comments: used by routeFeedController (addComment, getStatus)
CREATE TABLE IF NOT EXISTS route_feed_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status_id UUID NOT NULL REFERENCES route_feed_statuses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 16. route_feed_reactions: used by routeFeedController.react
CREATE TABLE IF NOT EXISTS route_feed_reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status_id UUID NOT NULL REFERENCES route_feed_statuses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  type TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(status_id, user_id)
);

-- 17. search_chatter_requests: used by searchChatterController (createRequest, getActiveRequests, makeOffer, acceptOffer, rejectOffer, deleteRequest)
CREATE TABLE IF NOT EXISTS search_chatter_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  origin TEXT NOT NULL,
  destination TEXT NOT NULL,
  date DATE,
  seats INTEGER NOT NULL,
  max_price NUMERIC,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 18. search_chatter_offers: used by searchChatterController (makeOffer, getOffers, acceptOffer, rejectOffer)
CREATE TABLE IF NOT EXISTS search_chatter_offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id UUID NOT NULL REFERENCES search_chatter_requests(id) ON DELETE CASCADE,
  driver_id UUID NOT NULL,
  price NUMERIC NOT NULL,
  departure_time TIMESTAMPTZ,
  vehicle_id UUID REFERENCES vehicles(id),
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 19. chats: used by chatsController (createChat, getUserChats, sendMessage, deleteChat)
CREATE TABLE IF NOT EXISTS chats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 20. chat_participants: used by chatsController (createChat, getUserChats, markAsRead, getUnreadCount)
CREATE TABLE IF NOT EXISTS chat_participants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  last_read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(chat_id, user_id)
);

-- 21. chat_messages: used by chatsController (getMessages, sendMessage, getUnreadCount)
CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL,
  content TEXT NOT NULL,
  type TEXT DEFAULT 'text',
  media_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
